### ISSUE TITLE
Whatsapp works with Chrome 60+ (no longer works)

### ISSUE THREAD

**Issue by 825i** [mimbrero/whatsapp-desktop-linux#12]
I now get this image when I open the app.

![Screenshot from 2022-02-24 20-02-09](https://user-images.githubusercontent.com/58630825/155581436-88c21acc-9a85-4d0d-ba1b-d24c200d8652.png)

**Comment by pythonInRelay** [comment]
Does not happen in the updated version.

**Comment by pythonInRelay** [comment]
Getting this again, now on the latest version. Is there some way this can be prevented from happening in the future?

**Comment by mimbrero** [comment]
Reopening the app again solves the issue.

I'll add something that automatically reloads the page if that message is displayed.

**Comment by nicocossiom** [comment]
yeah same just happened to me but even reopening and uninstalling the app doesn´t seem to fix it

**Comment by mimbrero** [comment]
> yeah same just happened to me but even reopening and uninstalling the app doesn´t seem to fix it

You have to close it from the tray menu, if you just click the window close button the app will still run in the background. Uninstalling while the app it's open (or in the background) doesn't kill the process, that's a Flatpak (and Linux in general) "feature", so I guess it's what's happening to you :(

I guess that after turning off your computer WhatsApp loads for you today, right?

Another way to reload the page is by pressing CTRL + R.

**Comment by skylarng89** [comment]
Doesn't work on my computer has well. It has never worked actually since I have been trying for over a month. It keeps displaying the message for me to update Chrome to 60+

**Comment by mimbrero** [comment]
Well, this is finally not happening with the [latest fix](https://github.com/mimbrero/whatsapp-desktop-linux/blob/main/src/fix/chrome-version-fix.ts), so I'm eventually closing this 🎉
