### ISSUE TITLE
Low resolution system tray icon on MX Linux

### ISSUE THREAD

**Issue by abhidesh128** [mimbrero/whatsapp-desktop-linux#16]
The tray icon showed in MX Linux, looks like does not have sufficient sharpness ? Now, this does not seem real issue to me, but how can I increase its resolution to sharpen it ?

Using the latest flatpak build on MX Linux 21 with xfce 4.16.

![image](https://user-images.githubusercontent.com/56992370/158837108-0f663e2f-3143-42ea-baa2-d60e45bab21a.png)

**Comment by abhidesh128** [comment]
Oh. I got it. It picks up the favicon of the page and shows it as the tray icon. As WhatsApp Web does not supply icon resolution more than 16 * 16px, I am seeing it in low res.

**Comment by mimbrero** [comment]
Don't worry. I made a custom icon and I'm no longer get it from the favicon, because it fixes another bug. [This is planned for the next release](https://github.com/mimbrero/whatsapp-desktop-linux/issues/10#issuecomment-1069524424).

**Comment by abhidesh128** [comment]
The new tray icon just works perfect..!! Thank you..!
