### ISSUE TITLE
don't require filesystem access to the full host

### ISSUE THREAD

**Issue by hferreiro** [mimbrero/whatsapp-desktop-linux#18]
I got this in the latest flatpak update:
```
New io.github.mimbrero.WhatsAppDesktop permissions:
    file access [1]     dbus access [2]

    [1] host
    [2] com.canonical.indicator.application, org.ayatana.indicator.application,
        org.kde.StatusNotifierWatcher
```

I think access to common XDG directories should be enough.

**Comment by frequential** [comment]
Unfortunately, not giving full permission on apps like these makes the user experience some incorrect behavior that they wouldn't expect. For me, not being able to drag n drop is not a big deal, but users switching to Linux expect _at least_ the same grade of functionality than in Windows or macOS.

Same dilemma with the Discord flatpak entry, they decided to remove host permissions, but there's always people complaining about weird behavior, which is not ideal.
