### ISSUE TITLE
Setting Tooltip

### ISSUE THREAD

**Issue by abhidesh128** [mimbrero/whatsapp-desktop-linux#19]
Currently, the new tray icon is just working fine. It shows generic tooltip - 

![image](https://user-images.githubusercontent.com/56992370/160068314-c338ac53-af8a-4b7d-89bb-8ab92e27ef62.png)

Can it be set as 'WhatsApp Desktop' using `this.tray.setToolTip('WhatsApp Desktop')` ?
I asked before raising PR because I am not sure how this will work on Flatpak on different systems.

**Comment by mimbrero** [comment]
Wow, I use GNOME and there are no tooltips in tray icons. Yes, feel free to make a PR. Does that remove that "icon" text too?

**Comment by abhidesh128** [comment]
Yes. It does remove that "icon" text, and is able to show unread messages as well..!

**Comment by abhidesh128** [comment]
Oh my, I used the word unread "messages". Could you please change it to "chats" (while merging) ?
