### ISSUE TITLE
Minimize to tray when  closing

### ISSUE THREAD

**Issue by JStyle21** [mimbrero/whatsapp-desktop-linux#25]
Hi,

Can the default closing behavior be changed to minimize to tray? it's a bit annoying having the app close down when i press the X button, no way to minimize apart from right click tray icon -> minimize to tray...

**Comment by RoinujNosde** [comment]
`Ctrl + W` minimizes the app to tray.

**Comment by JStyle21** [comment]
Why not have both? it's the normal behavior in any app

**Comment by RoinujNosde** [comment]
I agree with you. I just gave you an alternative.
Also, there already is a discussion on #22

**Comment by JStyle21** [comment]
It is a duplicate of #22
better track it there, thanks for the info and alternatives :)
