### ISSUE TITLE
Wrong System Tray Label when minimizing to Tray using Keybind on v1.2.2

### ISSUE THREAD

**Issue by J-onasJones** [mimbrero/whatsapp-desktop-linux#26]
Hi,
when minimizing the window to the tray, the label when right-clicking the tray Icon still says "Minimize to Tray". Clicking it will still reopen the window, so the label just doesn't update when closing with the keybind.

**Comment by mimbrero** [comment]
Thanks for reporting 😄

I cannot replicate this on GNOME with AppIndicator and KStatusNotifierItem support, but I think it's solved for the next release. 

Just reopen this again if it isn't.
