### ISSUE TITLE
Preview for links not being generated

### ISSUE THREAD

**Issue by EkanshdeepGupta** [mimbrero/whatsapp-desktop-linux#31]
**Description**
When sending a message containing a link, the preview generated for the link does not fetch any details about the linked webpage. When pasting a link in a chat from a phone or web.whatsapp.com, WhatsApp generates a preview for the url including a title and thumbnail. However, for links sent via whatsapp-desktop-linux, the preview only contains the url.

**To Reproduce**
1. Go to any chat.
2. Copy a link to a website in the chat
3. Wait a couple of seconds for the preview to be generated
4. The preview merely has the URL, not the title or thumbnail.

**Expected behavior**
The generated preview should have the title and thumbnail.

**Screenshots**
Preview generated by whatsapp-desktop-linux:
![Screenshot from 2022-07-03 18-25-17](https://user-images.githubusercontent.com/13527018/177059609-cddd6aa7-10fe-4d0b-a828-0f2013e8638d.png)

Preview generated by WhatsApp on phone:
![Screenshot from 2022-07-03 18-25-40](https://user-images.githubusercontent.com/13527018/177059610-43ee9a57-2deb-4992-ba67-f0571946736c.png)

**Environment**

 - Distro [ Fedora Linux 36 ]
 - Package [ Flatpak]
 - Desktop Environment or Window Manager [ Gnome 42.2 ]

**Comment by vivantart** [comment]
Yes. I was about to open an issue too.
+1 here.

- Flatpak
- Kubuntu 22.04

**Comment by mimbrero** [comment]
Hello, thanks for reporting :)

I think that this is an issue with the official WhatsApp web client, so I cannot do anything to solve this :(

But just to be sure, can you test this in web.whatsapp.com to check if this happens? Thanks :)

**Comment by vivantart** [comment]
> Hello, thanks for reporting :)
> 
> I think that this is an issue with the official WhatsApp web client, so I cannot do anything to solve this :(
> 
> But just to be sure, can you test this in web.whatsapp.com to check if this happens? Thanks :)

Yes, you're right. There was an article in Whatsapp FAQ mentioning about "unsupported features", and "link preview" was on the list. It's some limitation related to web API for now and seems that there is nothing devs can do about.

**Comment by vivantart** [comment]
https://faq.whatsapp.com/367577238567451/?helpref=uf_share

As you can see...

"We’re also aware that users are missing some features including link previews on WhatsApp Web, viewing live location on linked devices, better synching of deleted chats across devices, broadcast lists, sending and receiving messages to your own number, and syncing sticker packs from your phone to your linked device. We're working hard to reinstate as many of these as possible."

**Comment by EkanshdeepGupta** [comment]
Yes, you're right. I cannot understand why such a basic feature is not supported across the board by WhatsApp. Sorry for raising a spurious issue. I should have checked before, but I assumed since it's working on WhatsApp desktop apps it must also work on WhatsApp web.
