### ISSUE TITLE
No tray icon when using appimage

### ISSUE THREAD

**Issue by SayanChakroborty** [mimbrero/whatsapp-desktop-linux#33]
Starting from version 1.2.1 tray icon does not appear when using the appimage build. I have tested and version 1.2.0 works as expected but 1.2.1 and 1.2.2 does not show tray icon when appimage build is being used. I'm using Gnome 3.38.5 on Debian 11.5, using the extension [Appindicator](https://packages.debian.org/bullseye/gnome-shell-extension-appindicator). Please ask if you need more info.

**Comment by mimbrero** [comment]
Thanks for reporting :)
