### ISSUE TITLE
Icon is duplicated on KDE Plasma Task Manager

### ISSUE THREAD

**Issue by gchait** [mimbrero/whatsapp-desktop-linux#34]
- Happens on Kubuntu 22.04.1 LTS.
- Does not happen with GNOME's dock on Pop OS.
---
- Install the app from either the AppImage or the Flatpak.
- Pin it to Task Manager using the Application Launcher.
- Press the newly created icon.

The program launches as a separate icon, unable to be pinned itself.

After some messing around with the AppImage and making a custom desktop file, I managed to find a solution.
Since I'm still very new to all of this I don't know if this solution is acceptable or some kind of workaround to a larger issue.

This is the desktop file I have now:
```
[Desktop Entry]
Name=WhatsApp
Exec=/usr/local/bin/whatsapp %U
Type=Application
StartupWMClass=whatsapp-desktop-linux
Icon=io.github.mimbrero.WhatsAppDesktop
Comment=An unofficial WhatsApp client for Linux, built with Electron.
Terminal=false
Categories=Network;Chat;
```
Took some things from the Flatpak and others from Caprine as a working reference.

The particular line that seems to have fixed my issue and combined the icons is this one:
```
StartupWMClass=whatsapp-desktop-linux
```

**Comment by mimbrero** [comment]
Yes, that is the actual fix. 

It is [already implemented](https://github.com/mimbrero/whatsapp-desktop-linux/commit/ca32a1aa6f1e2696acd0c6fc4072e4103136e80a) thanks to @hmlendea, but not released. Please wait for the next release so that it's fixed on your system :)
