### ISSUE TITLE
Stuck at startup after the new update.

### ISSUE THREAD

**Issue by mannyoii** [mimbrero/whatsapp-desktop-linux#35]
Hi, the app is stuck at startup after updating it to the new version(1.2.3-1).
I'm using the Flatpak build from the Flathub.
Fedora Linux 36 (5.19.14-200.fc36.x86_64)
![Screenshot from 2022-10-12 21-42-56](https://user-images.githubusercontent.com/96596402/195394742-4d32e3b7-40d3-4225-b3d0-0ce75f93594d.png)

**Comment by MasterGeekMX** [comment]
Same thing here on Arch Linux (Kernel 5.19.13-arch1-1 ,flatpak release v1.2.3)

**Comment by mimbrero** [comment]
I've been testing and I didn't touch anything in the code that would cause this, the only thing I can think of is that I updated electron to the latest version.

> Tried erasing the ~/.var/app/com.github.eneshecan.WhatsAppForLinux/cache and nothing.

Deleting the whole `~/.var/app/com.github.eneshecan.WhatsAppForLinux` directory makes it work again :/

**Comment by mimbrero** [comment]
WhatsApp is always adding fake "bugs" to screw up these unofficial clients, like the "WhatsApp works with Chrome 60+", and now this.

I don't know what to do other than making everyone set up again their account, making the app deleting everything on update.

**Comment by Amansour23** [comment]
Same thing here on Fedora, 36

**Comment by AnAlligatorPear** [comment]
> Deleting the whole `~/.var/app/com.github.eneshecan.WhatsAppForLinux` directory makes it work again :/

That worked for me!

**Comment by mimbrero** [comment]
Ok, so v1.2.3-2 now cleans the storage data before starting. This isn't the workaround I wanted, but I cannot find out anything more. Meta wins this time.
