### ISSUE TITLE
Add "ctrl + =" hotkey to zoom in

### ISSUE THREAD

**Issue by eduardochaves1** [mimbrero/whatsapp-desktop-linux#37]
I figured out that `ctrl + -` decreases the view zoom on the app just like a browser, but the problem is that `ctrl + =` doesn't increases back to normal. I even tried with `ctrl + wheelup || wheeldown` using the mouse wheel and didn't work both ways. Now my whatsapp is like 50% zoom view and I cannot come back to normal...

![image](https://user-images.githubusercontent.com/95307858/197363793-abe537e1-1866-4d7e-8fbd-f4e7d64c0fcb.png)

As you can see in the image above, everything is shrinked now. And is not because it has a higher screen resolution (that print was taken in my second monitor in which is not even a 1080p screen resolution).

I tried to log out my account and uninstalled the app from my computer but it's still the same way.

**Comment by mimbrero** [comment]
Oh, I didn't even know that `ctrl + =` was another way to zoom in. I've always used `ctrl + +` to zoom in and `ctrl + 0` to go back to the default size. Try those shortcuts, and I'll add `ctrl + =` for the next version :)

**Comment by eduardochaves1** [comment]
> `ctrl + 0` to go back to the default size.

Thanks, didn't know that this shortcut went back to default zoom. Now I can use the app back to normal :smile:.

**Comment by sharvnaik10** [comment]
I was having the same issue, but now it is resolved, please add "ctrl + =" to zoom.
