### ISSUE TITLE
App crashes KDE Plasma desktop

### ISSUE THREAD

**Issue by danir-de** [mimbrero/whatsapp-desktop-linux#39]
After updating to KDE 5.26 from 5.25, this app seems to somehow crash the compositor.
Shortly after opening it, new windows and popups get rendered black and the desktop becomes more and more unresponsive.

Interestingly it doesn't matter if you have desktop effects enabled or not (SHIFT+ALT+F12).

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.6-1-MANJARO (64-bit)
Graphics Platform: X11
```

**Comment by mimbrero** [comment]
Good morning.

Is this happening only with this app? It's probably an electron bug.
Could you please paste here what happens when you run 'flatpak run io.github.mimbrero.WhatsAppDesktop' in the terminal? Thanks :)

**Comment by danir-de** [comment]
Good morning.

This seems to be a Plasma 5.26 bug - which get's triggered when you get many notifications.

See [https://forum.manjaro.org/t/kde-plasma-5-26-x-stability-inquiry/125823/43](https://forum.manjaro.org/t/kde-plasma-5-26-x-stability-inquiry/125823/43?u=danir.de).

I'm closing this issue - sorry for disturbing.

**Comment by mimbrero** [comment]
Oh, sure :)

> I'm closing this issue - sorry for disturbing.

No! I should be the one saying sorry for the late reply. Thank you for collaborating :)
