### ISSUE TITLE
Chrome > 60 issue

### ISSUE THREAD

**Issue by iamdebadipti** [mimbrero/whatsapp-desktop-linux#4]
Awesome work buddy! It was working as expected, but now when I open it says "browser not supported Chrome > 60 required".

**Comment by mimbrero** [comment]
I just started investigating this issue. The user agent tells the page that you are using Chrome 97, so the version isn't problem. WhatsApp is bugging for some reason when there's an update of the web.whatsapp.com code and shows the Chrome version error...

The only quick fix for now is deleting the user data, everything inside
`/home/YOUR_USER/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux`

**Comment by carallo** [comment]
Don't know if it's related, but I cannot seem to be able to connect my phone. After I scan the QR code it starts loading but then suddenly goes back to the QR code page. Keep in mind that I have enabled the "beta" feature which allows for using Whatsapp Web even when the phone is not connected to the internet, though that hasn't been an issue with other Whatsapp Webapps.

**Comment by mimbrero** [comment]
> Don't know if it's related, but I cannot seem to be able to connect my phone. After I scan the QR code it starts loading but then suddenly goes back to the QR code page. Keep in mind that I have enabled the "beta" feature which allows for using Whatsapp Web even when the phone is not connected to the internet, though that hasn't been an issue with other Whatsapp Webapps.

I also use the beta version, and that has never happened to me. Your issue is probably WhatsApp's fault, as I only open the official page in a small browser. Does it work in your browser, https://web.whatsapp.com?

**Comment by mimbrero** [comment]
@iamdebadipti try opening the app again, and tell me if you see the Chrome version message. If so, reopen the app. What happens? I think WhatsApp just fixed this bug...??

**Comment by iamdebadipti** [comment]
@mimbrero the bug seems to be fixed. I have reinstalled the app, and it seamlessly logged me in after the QR code scan.

**Comment by carallo** [comment]
> > Don't know if it's related, but I cannot seem to be able to connect my phone. After I scan the QR code it starts loading but then suddenly goes back to the QR code page. Keep in mind that I have enabled the "beta" feature which allows for using Whatsapp Web even when the phone is not connected to the internet, though that hasn't been an issue with other Whatsapp Webapps.
> 
> I also use the beta version, and that has never happened to me. Your issue is probably WhatsApp's fault, as I only open the official page in a small browser. Does it work in your browser, https://web.whatsapp.com?

Yes, all other Whatsapp webapps were working. Anyway, today I just uninstalled and reinstalled the app (deleting config folder) and it magically worked, no idea why. Thanks anyway!
