### ISSUE TITLE
Whatsapp Links don't open in Whatspp Desktop x-scheme-handler/whatsapp

### ISSUE THREAD

**Issue by berserkwarwolf** [mimbrero/whatsapp-desktop-linux#44]
![Screenshot from 2023-03-06 14-46-51](https://user-images.githubusercontent.com/13665922/223190247-7e27a73e-073b-4b4b-a803-f9209ba22462.png)
![Screenshot from 2023-03-06 14-47-20](https://user-images.githubusercontent.com/13665922/223190254-f69943e1-2455-48ec-af5b-4dea6fffbd2a.png)

**Comment by mmaluff** [comment]
If I do

`xdg-mime default io.github.mimbrero.WhatsAppDesktop.desktop 'x-scheme-handler/whatsapp'`

it actually does open the app, but it doesn't open the conversation based on the link.

**Comment by jmflaherty** [comment]
Same as @mmaluff , but I set it with `xdg-settings set default-url-scheme-handler whatsapp io.github.mimbrero.WhatsAppDesktop.desktop`.

**Comment by berserkwarwolf** [comment]
@mmaluff @jmflaherty there's another Flatpak app, called "Whatsapp for Linux" it opens links just fine. I switched to that when I found out that @mimbrero 's app is unmaintained, since the last commit was october 13 2022.

**Comment by mcdemon05** [comment]
also faced this problem :(
Did the author really abandon the application?
