### ISSUE TITLE
[Feature Request] Tray icon

### ISSUE THREAD

**Issue by jr1991-g** [mimbrero/whatsapp-desktop-linux#6]
This client works really well. I'm afraid to ask, but would it be possible to add a tray icon? That would make it perfect.

**Comment by mimbrero** [comment]
Thank you!

I tried to recreate the official Windows app, which has no tray icon, but yeah I should add it. 

Following GNOME guidelines, it should have minimal functionality, as some desktops (GNOME primarily) don't use tray icons. However, background activity and a simple icon to show, hide and close the app should be fine. How about it?

**Comment by jr1991-g** [comment]
I think that would be great! If you want a tester here I am.

**Comment by marcelovbcfilho** [comment]
I was looking through eletrcon documentation and I found that is possible to update dynamically the tray icon, *SO* I would like to know if when implementing would be possible to update the tray icon with the amount of unread messages, like is in the browser version.

The image show an exemple about what I was thinking. But I believe that to follow the gnome behavior the icon should be monochromatic.

![Screenshot from 2022-02-04 23-32-46](https://user-images.githubusercontent.com/51462138/152625684-568f1cde-c793-42eb-9add-937577f06b3a.png)


Issue saying that is possible to update dynamically the tray icon
https://stackoverflow.com/a/43695301

**Comment by mimbrero** [comment]
> I was looking through eletrcon documentation and I found that is possible to update dynamically the tray icon, _SO_ I would like to know if when implementing would be possible to update the tray icon with the amount of unread messages, like is in the browser version.
> 
> The image show an exemple about what I was thinking. But I believe that to follow the gnome behavior the icon should be monochromatic.
> 
> ![Screenshot from 2022-02-04 23-32-46](https://user-images.githubusercontent.com/51462138/152625684-568f1cde-c793-42eb-9add-937577f06b3a.png)
> 
> Issue saying that is possible to update dynamically the tray icon https://stackoverflow.com/a/43695301

Yeah, it's possible, also with the app icon, which I was already implementing 😄

**Comment by mimbrero** [comment]
@marcelovbcfilho how high does the count go in that icon? up 9 or what?

**Comment by pythonInRelay** [comment]
> 

It goes up to (99+) which is excessive. You could cut it at (9+) or something, or even just set a static (1) no matter how many replies there are.

The tray icon options could be:

1. Show app
2. Settings (if not too difficult to do)
3. Mute notifications (if not too difficult to do)
4. Quit

Two and Three are not so important really though.

**Comment by mimbrero** [comment]
Thanks for the information @pythonInRelay. 

I'll work on this ASAP, but I'm a bit busy, so give me some days :)
