### ISSUE TITLE
Is it possible to scale the app DPI?

### ISSUE THREAD

**Issue by pythonInRelay** [mimbrero/whatsapp-desktop-linux#7]
I'm running a multi-monitor setup like so:

3840x2160 in portrait mode (for reading)
3440x1440 in landscape mode (main)

On the 3840x2160 display the Whatsapp Desktop text is absolutely tiny. I like to run my chat apps on the vertical/portrait display like so:

1. Slack
2. Whatsapp
3. Discord

Now I could change the scaling of my entire desktop, but then that changes the scaling for my main monitor too, which I don't want to. I could also enable fractional scaling which allows me to set independent scaling for each monitor, but then dozens of apps display incorrectly and some applications cannot properly detect my EITHER screen's resolution or refresh rate. (eg. Steam, CS:GO, Zoho, etc).

**Both Slack AND Discord** have a feature that allows you to set the scale of the entire UI within the app, so I have increased both by 75% and they're sharp and crystal clear. How do I do this for Whatsapp Desktop, seeing as there is no way to increase the scale in the UI and it is the last app I wish to have on that monitor which I cannot read the small text.

**Comment by pythonInRelay** [comment]
Any chance we can get a build with this soon? Or could you tell me how to build one from source that won't scream at me in terminal.

**Comment by mimbrero** [comment]
I've scheduled this feature for [the next version](https://github.com/mimbrero/whatsapp-desktop-linux/milestone/1), but you can run the app by cloning the repo, running `npm install` (just the first time) and `npm start` (every time you want to start the app) inside your local repo directory
